### PR TITLE
Update mcr.cpp

### PR DESCRIPTION
**Pull request by susie30**
test: just add some space to ajust the format

### CODE REVIEW

**Comment by Carlone123** [comment]
this code is very good！！

**Comment by LZQ0819** [comment]
Yeap

**Review by ccxzyhm — COMMENTED** [review]
Nice change

**Review by susie30 — COMMENTED** [review]
JUST FOR TEST

**Review by LZQ0819 — COMMENTED** [review]
Maybe it should

**Review by ccxzyhm — COMMENTED** [review]
correct

**Pull request merged**
